# Netlify/Cloudflare Pages build configuration
[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.150.1"
  HUGO_ENV = "production"
  NODE_VERSION = "18"

# Redirect rules for admin
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200