# Cloudflare Pages configuration for Hugo site
name = "mgrnz-blog"
compatibility_date = "2024-10-26"
pages_build_output_dir = "public"

[env.production]
HUGO_VERSION = "0.150.1"
HUGO_ENV = "production"