# Cloudflare Pages configuration for Hugo site
name = "mgrnz-blog"
compatibility_date = "2024-10-26"

[build]
command = "hugo --gc --minify"
cwd = "."
publish = "public"

[build.environment]
HUGO_VERSION = "0.147.8"
HUGO_ENV = "production"
NODE_VERSION = "18"