name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      triggered_by:
        description: 'Source that triggered the deployment'
        required: false
        default: 'manual'
      timestamp:
        description: 'Timestamp of trigger'
        required: false

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive
          git submodule status

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.150.1'
          extended: true

      - name: Verify Hugo installation
        run: hugo version

      - name: Build with Hugo
        run: |
          echo "Building Hugo site..."
          hugo --gc --minify
          echo "Build completed. Checking output..."
          ls -la public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: mgrnz.com
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
