# .github/workflows/rebuild-on-schedule.yml

name: Rebuild Hugo on Schedule

on:
  # Allows this workflow to be triggered by the Supabase cron job
  workflow_dispatch:
    inputs:
      source:
        description: 'The source of the trigger'
        required: false
        default: 'supabase-cron'

jobs:
  trigger-deploy:
    uses: ./.github/workflows/deploy-gh-pages.yml
    secrets: inherit

